### ISSUE TITLE
弱弱地问一句要如何使用。

### ISSUE THREAD

**Issue by JoinGitHubBa** [Kr328/V2rayDomains2Clash#6]
实在是找不出配置有什么问题，希望可以帮帮我。
```
mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
proxy-providers:
  Subscription:
    type: http
    url: https://api.example.com/Subscription
    interval: 3600
    path: ./proxy-providers/Subscription.yaml
    health-check:
      enable: true
      interval: 3600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: Google
    type: select
    use:
      - Subscription
rules:
  - RULE-SET,Google,Google
rule-providers:
  Google:
    type: http
    behavior: classical
    url: https://rules.kr328.app/google.yaml
    path: ./rule-providers/google
    interval: 86400
  Facebook:
    type: http
    behavior: classical
    url: https://rules.kr328.app/facebook.yaml
    path: ./rule-providers/facebook
    interval: 86400
```
![Snipaste_2021-05-23_10-58-04](https://user-images.githubusercontent.com/83970503/119246846-79b13d00-bbb7-11eb-945e-d2f74b6f5403.png)
![Snipaste_2021-05-23_11-08-47](https://user-images.githubusercontent.com/83970503/119246851-7f0e8780-bbb7-11eb-9bc0-d34649e71394.png)

google.yaml 用这种格式就没问题
```
payload:
  - DOMAIN,aod.itunes.apple.com
  - DOMAIN,api.smoot.apple.cn
  - DOMAIN,appldnld.apple.com
  - DOMAIN,apptrailers.itunes.apple.com
  - DOMAIN,gs-loc-cn.apple.com
  - DOMAIN,iosapps.itunes.apple.com
  - DOMAIN,music.apple.com
  - DOMAIN,mvod.itunes.apple.com
  - DOMAIN,osxapps.itunes.apple.com
  - DOMAIN,supportdownload.apple.com
  - DOMAIN,swcdn.apple.com
  - DOMAIN,updates-http.cdn-apple.com
  - DOMAIN-SUFFIX,ls.apple.com
  - DOMAIN-SUFFIX,mzstatic.com
```
